# Generated by Django 5.2.3 on 2025-06-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reminder', 'Przypomnienie o dostawie'), ('confirmation', 'Potwierdzenie dostawy'), ('block', 'Wstrzymanie dostawy')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
