# Generated by Django 5.2.3 on 2025-06-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('warehouse', 'Magazyn'), ('client', 'U klienta'), ('service', 'Serwis'), ('scrap', 'Złom')], default='warehouse', max_length=20)),
                ('owner', models.CharField(choices=[('piastpol', 'Piastpol'), ('lease', 'Dzierżawa'), ('client', 'Klient')], default='piastpol', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.deliveryaddress')),
            ],
        ),
    ]
